#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RottenTomatoes.Resource", IsApplication=true)]

namespace RottenTomatoes
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PullToRefresharp.Resource.Attribute.contentViewId = global::RottenTomatoes.Resource.Attribute.contentViewId;
			global::PullToRefresharp.Resource.Attribute.headerIconDrawable = global::RottenTomatoes.Resource.Attribute.headerIconDrawable;
			global::PullToRefresharp.Resource.Attribute.headerId = global::RottenTomatoes.Resource.Attribute.headerId;
			global::PullToRefresharp.Resource.Attribute.headerTextColor = global::RottenTomatoes.Resource.Attribute.headerTextColor;
			global::PullToRefresharp.Resource.Attribute.ptrHeaderBackground = global::RottenTomatoes.Resource.Attribute.ptrHeaderBackground;
			global::PullToRefresharp.Resource.Attribute.pullDownProgressIndicatorId = global::RottenTomatoes.Resource.Attribute.pullDownProgressIndicatorId;
			global::PullToRefresharp.Resource.Attribute.pullDownTension = global::RottenTomatoes.Resource.Attribute.pullDownTension;
			global::PullToRefresharp.Resource.Attribute.pullEnabled = global::RottenTomatoes.Resource.Attribute.pullEnabled;
			global::PullToRefresharp.Resource.Attribute.pullToRefreshText = global::RottenTomatoes.Resource.Attribute.pullToRefreshText;
			global::PullToRefresharp.Resource.Attribute.refreshingText = global::RottenTomatoes.Resource.Attribute.refreshingText;
			global::PullToRefresharp.Resource.Attribute.releaseToRefreshText = global::RottenTomatoes.Resource.Attribute.releaseToRefreshText;
			global::PullToRefresharp.Resource.Attribute.snapbackDuration = global::RottenTomatoes.Resource.Attribute.snapbackDuration;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_end = global::RottenTomatoes.Resource.Color.ptrsharp_sb_gradient_end;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_gradient_start = global::RottenTomatoes.Resource.Color.ptrsharp_sb_gradient_start;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_header_text = global::RottenTomatoes.Resource.Color.ptrsharp_sb_header_text;
			global::PullToRefresharp.Resource.Color.ptrsharp_sb_header_text_shadow = global::RottenTomatoes.Resource.Color.ptrsharp_sb_header_text_shadow;
			global::PullToRefresharp.Resource.Drawable.progress_medium_holo = global::RottenTomatoes.Resource.Drawable.progress_medium_holo;
			global::PullToRefresharp.Resource.Drawable.ptrsharp_serious_business_gradient = global::RottenTomatoes.Resource.Drawable.ptrsharp_serious_business_gradient;
			global::PullToRefresharp.Resource.Drawable.serious_business_arrow = global::RottenTomatoes.Resource.Drawable.serious_business_arrow;
			global::PullToRefresharp.Resource.Drawable.serious_business_arrow2 = global::RottenTomatoes.Resource.Drawable.serious_business_arrow2;
			global::PullToRefresharp.Resource.Drawable.spinner_20_inner_holo = global::RottenTomatoes.Resource.Drawable.spinner_20_inner_holo;
			global::PullToRefresharp.Resource.Drawable.spinner_20_outer_holo = global::RottenTomatoes.Resource.Drawable.spinner_20_outer_holo;
			global::PullToRefresharp.Resource.Id.header = global::RottenTomatoes.Resource.Id.header;
			global::PullToRefresharp.Resource.Id.header_container = global::RottenTomatoes.Resource.Id.header_container;
			global::PullToRefresharp.Resource.Id.icon = global::RottenTomatoes.Resource.Id.icon;
			global::PullToRefresharp.Resource.Id.pullDownProgressIndicator = global::RottenTomatoes.Resource.Id.pullDownProgressIndicator;
			global::PullToRefresharp.Resource.Id.text = global::RottenTomatoes.Resource.Id.text;
			global::PullToRefresharp.Resource.Layout.ptrsharp_header = global::RottenTomatoes.Resource.Layout.ptrsharp_header;
			global::PullToRefresharp.Resource.String.library_name = global::RottenTomatoes.Resource.String.library_name;
			global::PullToRefresharp.Resource.String.ptrsharp_pull_to_refresh = global::RottenTomatoes.Resource.String.ptrsharp_pull_to_refresh;
			global::PullToRefresharp.Resource.String.ptrsharp_refreshing = global::RottenTomatoes.Resource.String.ptrsharp_refreshing;
			global::PullToRefresharp.Resource.String.ptrsharp_release_to_refresh = global::RottenTomatoes.Resource.String.ptrsharp_release_to_refresh;
			global::PullToRefresharp.Resource.Style.HoloProgressMedium = global::RottenTomatoes.Resource.Style.HoloProgressMedium;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_contentViewId = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper_contentViewId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper_headerIconDrawable;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerId = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper_headerId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_headerTextColor = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper_headerTextColor;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper_ptrHeaderBackground;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper_pullDownProgressIndicatorId;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullDownTension = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper_pullDownTension;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullEnabled = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper_pullEnabled;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper_pullToRefreshText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_refreshingText = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper_refreshingText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper_releaseToRefreshText;
			global::PullToRefresharp.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration = global::RottenTomatoes.Resource.Styleable.PullToRefresharpWrapper_snapbackDuration;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int contentViewId = 2130771969;
			
			// aapt resource value: 0x7f01000a
			public const int headerIconDrawable = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int headerId = 2130771968;
			
			// aapt resource value: 0x7f010009
			public const int headerTextColor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int ptrHeaderBackground = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int pullDownProgressIndicatorId = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int pullDownTension = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int pullEnabled = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int pullToRefreshText = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int refreshingText = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int releaseToRefreshText = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int snapbackDuration = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int ptrsharp_sb_gradient_end = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int ptrsharp_sb_gradient_start = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int ptrsharp_sb_header_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ptrsharp_sb_header_text_shadow = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fresh = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int popcorn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int progress_medium_holo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ptrsharp_serious_business_gradient = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int rotten = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int serious_business_arrow = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int serious_business_arrow2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int spinner_20_inner_holo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int spinner_20_outer_holo = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070027
			public const int actor1 = 2131165223;
			
			// aapt resource value: 0x7f070040
			public const int actor10 = 2131165248;
			
			// aapt resource value: 0x7f07002a
			public const int actor2 = 2131165226;
			
			// aapt resource value: 0x7f07002d
			public const int actor3 = 2131165229;
			
			// aapt resource value: 0x7f070030
			public const int actor4 = 2131165232;
			
			// aapt resource value: 0x7f070033
			public const int actor5 = 2131165235;
			
			// aapt resource value: 0x7f070035
			public const int actor6 = 2131165237;
			
			// aapt resource value: 0x7f070037
			public const int actor7 = 2131165239;
			
			// aapt resource value: 0x7f07003a
			public const int actor8 = 2131165242;
			
			// aapt resource value: 0x7f07003d
			public const int actor9 = 2131165245;
			
			// aapt resource value: 0x7f070007
			public const int actors = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int caption = 2131165193;
			
			// aapt resource value: 0x7f070025
			public const int cast_label = 2131165221;
			
			// aapt resource value: 0x7f070028
			public const int characters1 = 2131165224;
			
			// aapt resource value: 0x7f070041
			public const int characters10 = 2131165249;
			
			// aapt resource value: 0x7f07002b
			public const int characters2 = 2131165227;
			
			// aapt resource value: 0x7f07002e
			public const int characters3 = 2131165230;
			
			// aapt resource value: 0x7f070031
			public const int characters4 = 2131165233;
			
			// aapt resource value: 0x7f070034
			public const int characters5 = 2131165236;
			
			// aapt resource value: 0x7f070036
			public const int characters6 = 2131165238;
			
			// aapt resource value: 0x7f070038
			public const int characters7 = 2131165240;
			
			// aapt resource value: 0x7f07003b
			public const int characters8 = 2131165243;
			
			// aapt resource value: 0x7f07003e
			public const int characters9 = 2131165246;
			
			// aapt resource value: 0x7f070043
			public const int consensus = 2131165251;
			
			// aapt resource value: 0x7f070020
			public const int director = 2131165216;
			
			// aapt resource value: 0x7f070006
			public const int freshness = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int freshnessIcon = 2131165189;
			
			// aapt resource value: 0x7f070023
			public const int genre = 2131165219;
			
			// aapt resource value: 0x7f07006f
			public const int header = 2131165295;
			
			// aapt resource value: 0x7f07006e
			public const int header_container = 2131165294;
			
			// aapt resource value: 0x7f070071
			public const int icon = 2131165297;
			
			// aapt resource value: 0x7f070045
			public const int icon1 = 2131165253;
			
			// aapt resource value: 0x7f07006b
			public const int icon10 = 2131165291;
			
			// aapt resource value: 0x7f07004a
			public const int icon2 = 2131165258;
			
			// aapt resource value: 0x7f07004e
			public const int icon3 = 2131165262;
			
			// aapt resource value: 0x7f070052
			public const int icon4 = 2131165266;
			
			// aapt resource value: 0x7f070057
			public const int icon5 = 2131165271;
			
			// aapt resource value: 0x7f07005b
			public const int icon6 = 2131165275;
			
			// aapt resource value: 0x7f07005f
			public const int icon7 = 2131165279;
			
			// aapt resource value: 0x7f070063
			public const int icon8 = 2131165283;
			
			// aapt resource value: 0x7f070067
			public const int icon9 = 2131165287;
			
			// aapt resource value: 0x7f070010
			public const int imageView1 = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int imageView2 = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int imageView3 = 2131165206;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout1 = 2131165194;
			
			// aapt resource value: 0x7f07002f
			public const int linearLayout10 = 2131165231;
			
			// aapt resource value: 0x7f070032
			public const int linearLayout11 = 2131165234;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout12 = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout13 = 2131165188;
			
			// aapt resource value: 0x7f070039
			public const int linearLayout14 = 2131165241;
			
			// aapt resource value: 0x7f07003c
			public const int linearLayout15 = 2131165244;
			
			// aapt resource value: 0x7f07003f
			public const int linearLayout16 = 2131165247;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout17 = 2131165198;
			
			// aapt resource value: 0x7f070044
			public const int linearLayout18 = 2131165252;
			
			// aapt resource value: 0x7f070049
			public const int linearLayout19 = 2131165257;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout2 = 2131165184;
			
			// aapt resource value: 0x7f07004d
			public const int linearLayout20 = 2131165261;
			
			// aapt resource value: 0x7f070051
			public const int linearLayout21 = 2131165265;
			
			// aapt resource value: 0x7f070056
			public const int linearLayout22 = 2131165270;
			
			// aapt resource value: 0x7f07005a
			public const int linearLayout23 = 2131165274;
			
			// aapt resource value: 0x7f07005e
			public const int linearLayout24 = 2131165278;
			
			// aapt resource value: 0x7f070062
			public const int linearLayout25 = 2131165282;
			
			// aapt resource value: 0x7f070066
			public const int linearLayout26 = 2131165286;
			
			// aapt resource value: 0x7f07006a
			public const int linearLayout27 = 2131165290;
			
			// aapt resource value: 0x7f070046
			public const int linearLayout28 = 2131165254;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout3 = 2131165201;
			
			// aapt resource value: 0x7f070053
			public const int linearLayout31 = 2131165267;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout4 = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout5 = 2131165205;
			
			// aapt resource value: 0x7f070018
			public const int linearLayout6 = 2131165208;
			
			// aapt resource value: 0x7f070026
			public const int linearLayout7 = 2131165222;
			
			// aapt resource value: 0x7f070029
			public const int linearLayout8 = 2131165225;
			
			// aapt resource value: 0x7f07002c
			public const int linearLayout9 = 2131165228;
			
			// aapt resource value: 0x7f07000c
			public const int listView1 = 2131165196;
			
			// aapt resource value: 0x7f07001e
			public const int movie_info = 2131165214;
			
			// aapt resource value: 0x7f070021
			public const int mpaa_rating = 2131165217;
			
			// aapt resource value: 0x7f070070
			public const int pullDownProgressIndicator = 2131165296;
			
			// aapt resource value: 0x7f07000b
			public const int pulltorefresharp_android_views_ViewWrapper1 = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int ratingRuntime = 2131165192;
			
			// aapt resource value: 0x7f070024
			public const int release_date = 2131165220;
			
			// aapt resource value: 0x7f070048
			public const int review1 = 2131165256;
			
			// aapt resource value: 0x7f07006d
			public const int review10 = 2131165293;
			
			// aapt resource value: 0x7f07004c
			public const int review2 = 2131165260;
			
			// aapt resource value: 0x7f070050
			public const int review3 = 2131165264;
			
			// aapt resource value: 0x7f070055
			public const int review4 = 2131165269;
			
			// aapt resource value: 0x7f070059
			public const int review5 = 2131165273;
			
			// aapt resource value: 0x7f07005d
			public const int review6 = 2131165277;
			
			// aapt resource value: 0x7f070061
			public const int review7 = 2131165281;
			
			// aapt resource value: 0x7f070065
			public const int review8 = 2131165285;
			
			// aapt resource value: 0x7f070069
			public const int review9 = 2131165289;
			
			// aapt resource value: 0x7f070047
			public const int reviewer1 = 2131165255;
			
			// aapt resource value: 0x7f07006c
			public const int reviewer10 = 2131165292;
			
			// aapt resource value: 0x7f07004b
			public const int reviewer2 = 2131165259;
			
			// aapt resource value: 0x7f07004f
			public const int reviewer3 = 2131165263;
			
			// aapt resource value: 0x7f070054
			public const int reviewer4 = 2131165268;
			
			// aapt resource value: 0x7f070058
			public const int reviewer5 = 2131165272;
			
			// aapt resource value: 0x7f07005c
			public const int reviewer6 = 2131165276;
			
			// aapt resource value: 0x7f070060
			public const int reviewer7 = 2131165280;
			
			// aapt resource value: 0x7f070064
			public const int reviewer8 = 2131165284;
			
			// aapt resource value: 0x7f070068
			public const int reviewer9 = 2131165288;
			
			// aapt resource value: 0x7f070042
			public const int reviews = 2131165250;
			
			// aapt resource value: 0x7f070022
			public const int runtime = 2131165218;
			
			// aapt resource value: 0x7f07000d
			public const int scrollView1 = 2131165197;
			
			// aapt resource value: 0x7f07001f
			public const int synopsis = 2131165215;
			
			// aapt resource value: 0x7f070072
			public const int text = 2131165298;
			
			// aapt resource value: 0x7f070014
			public const int textView2 = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int textView3 = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int textView4 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int textView5 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int textView6 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int textView7 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int textView8 = 2131165213;
			
			// aapt resource value: 0x7f070001
			public const int thumbnail = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int title = 2131165187;
			
			// aapt resource value: 0x7f07000f
			public const int title_bar = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListSeparator = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MoviePageLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ptrsharp_header = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int app_name = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int hello = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ptrsharp_pull_to_refresh = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int ptrsharp_refreshing = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int ptrsharp_release_to_refresh = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int HoloProgressMedium = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Mono_Android_Theme_Splash = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefresharpWrapper = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int PullToRefresharpWrapper_contentViewId = 1;
			
			// aapt resource value: 10
			public const int PullToRefresharpWrapper_headerIconDrawable = 10;
			
			// aapt resource value: 0
			public const int PullToRefresharpWrapper_headerId = 0;
			
			// aapt resource value: 9
			public const int PullToRefresharpWrapper_headerTextColor = 9;
			
			// aapt resource value: 8
			public const int PullToRefresharpWrapper_ptrHeaderBackground = 8;
			
			// aapt resource value: 2
			public const int PullToRefresharpWrapper_pullDownProgressIndicatorId = 2;
			
			// aapt resource value: 4
			public const int PullToRefresharpWrapper_pullDownTension = 4;
			
			// aapt resource value: 11
			public const int PullToRefresharpWrapper_pullEnabled = 11;
			
			// aapt resource value: 5
			public const int PullToRefresharpWrapper_pullToRefreshText = 5;
			
			// aapt resource value: 7
			public const int PullToRefresharpWrapper_refreshingText = 7;
			
			// aapt resource value: 6
			public const int PullToRefresharpWrapper_releaseToRefreshText = 6;
			
			// aapt resource value: 3
			public const int PullToRefresharpWrapper_snapbackDuration = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
